/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as layoutRouteRouteImport } from './routes/(layout)/route'
import { Route as layoutIndexRouteImport } from './routes/(layout)/index'

const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutIndexRoute = layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof layoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof layoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/(layout)/': typeof layoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(layout)' | '/(layout)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)/': {
      id: '/(layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof layoutIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
  }
}

interface layoutRouteRouteChildren {
  layoutIndexRoute: typeof layoutIndexRoute
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layoutIndexRoute: layoutIndexRoute,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  layoutRouteRoute: layoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
